#!/bin/bash

docker run --name fambot-postgres -e POSTGRES_PASSWORD=$POSTGRES_PASSWORD -p 5432:5432 -d postgres

# You need to have the postgres cli client installed
# sudo apt install postgresql-client

psql -v ON_ERROR_STOP=1 --username "postgres" --dbname "postgres" --host "localhost" <<-EOSQL
    DROP TABLE IF EXISTS fam;
    CREATE TABLE IF NOT EXISTS fam (
        id text PRIMARY KEY,
        name text NOT NULL,
        experience smallint NOT NULL,
        rank smallint NOT NULL,
        is_fam boolean NOT NULL,
        title text
    )
EOSQL