name: Fambot Docker Build
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    env:         
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}  

    steps:

    - name: Docker Login
      uses: docker/login-action@v1.10.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
    - name: Build and Push the Docker image
      run: docker buildx build --push --platform linux/arm/v7 -t mulchbutler/fambot .
